---
:classics-tab-frontend-none: {}
:classics-tab-frontend-stimulus:
  :main-tab-starters-gemfile: true
  :main-tab-starters-bundle: true
  :main-tab-frontend-javascript: true
  :main-tab-frontend-webpacker: false
  :main-tab-frontend-turbolinks: true
  :main-tab-frontend-yarn: true
:classics-tab-frontend-stimulus-reflex:
  :main-tab-starters-gemfile: true
  :main-tab-starters-bundle: true
  :main-tab-mains-actioncable: true
  :main-tab-frontend-javascript: true
  :main-tab-frontend-webpacker: false
  :main-tab-frontend-turbolinks: true
  :main-tab-frontend-yarn: true
:classics-tab-testing-none:
  :main-tab-testing-minitest: false
  :main-tab-testing-system: false
:classics-tab-testing-minitest:
  :main-tab-testing-minitest: true
:classics-tab-testing-rspec:
  :main-tab-testing-minitest: false
:classics-tab-css-none: {}
:classics-tab-css-tailwind:
  :main-tab-starters-gemfile: true
  :main-tab-starters-bundle: true
  :main-tab-frontend-javascript: true
  :main-tab-frontend-webpacker: false
  :main-tab-frontend-turbolinks: true
  :main-tab-frontend-yarn: true
:classics-tab-css-bootstrap:
  :main-tab-starters-gemfile: true
  :main-tab-starters-bundle: true
  :main-tab-frontend-javascript: true
  :main-tab-frontend-webpacker: false
  :main-tab-frontend-turbolinks: true
  :main-tab-frontend-yarn: true