---
css-bootstrap@frontend-none@testing-minitest: 'https://www.railsbytes.com/script/VMys5p'
css-bootstrap@frontend-none@testing-none: 'https://www.railsbytes.com/script/VMys5p'
css-bootstrap@frontend-none@testing-rspec: 'https://www.railsbytes.com/script/Vwys0J'
css-bootstrap@frontend-stimulus-reflex@testing-minitest: 'https://www.railsbytes.com/script/XnJs52'
css-bootstrap@frontend-stimulus-reflex@testing-none: 'https://www.railsbytes.com/script/XnJs52'
css-bootstrap@frontend-stimulus-reflex@testing-rspec: 'https://www.railsbytes.com/script/zyvso6'
css-bootstrap@frontend-stimulus@testing-minitest: 'https://www.railsbytes.com/script/xjNsAn'
css-bootstrap@frontend-stimulus@testing-none: 'https://www.railsbytes.com/script/xjNsAn'
css-bootstrap@frontend-stimulus@testing-rspec: 'https://www.railsbytes.com/script/VAjskW'
css-none@frontend-none@testing-minitest: ''
css-none@frontend-none@testing-none: ''
css-none@frontend-none@testing-rspec: 'https://www.railsbytes.com/script/VD7sra'
css-none@frontend-stimulus-reflex@testing-minitest: 'https://www.railsbytes.com/script/zr4s0Y'
css-none@frontend-stimulus-reflex@testing-none: 'https://www.railsbytes.com/script/zr4s0Y'
css-none@frontend-stimulus-reflex@testing-rspec: 'https://www.railsbytes.com/script/VqqsAD'
css-none@frontend-stimulus@testing-minitest: 'https://www.railsbytes.com/script/V33s33'
css-none@frontend-stimulus@testing-none: 'https://www.railsbytes.com/script/V33s33'
css-none@frontend-stimulus@testing-rspec: 'https://www.railsbytes.com/script/XnJsb5'
css-tailwind@frontend-none@testing-minitest: 'https://www.railsbytes.com/script/X8BsGy'
css-tailwind@frontend-none@testing-none: 'https://www.railsbytes.com/script/X8BsGy'
css-tailwind@frontend-none@testing-rspec: 'https://www.railsbytes.com/script/V4Ysjj'
css-tailwind@frontend-stimulus-reflex@testing-minitest: 'https://www.railsbytes.com/script/z0gsd8'
css-tailwind@frontend-stimulus-reflex@testing-none: 'https://www.railsbytes.com/script/z0gsd8'
css-tailwind@frontend-stimulus-reflex@testing-rspec: 'https://www.railsbytes.com/script/XE5s7O'
css-tailwind@frontend-stimulus@testing-minitest: 'https://www.railsbytes.com/script/zyvsbW'
css-tailwind@frontend-stimulus@testing-none: 'https://www.railsbytes.com/script/zyvsbW'
css-tailwind@frontend-stimulus@testing-rspec: 'https://www.railsbytes.com/script/Xo5s9m'