---
:main_tab:
  :ui_config:
    :base_setup:
      :omakase:
        true: ''
        false: ''
      :api:
        true: ''
        false: ''
      :early:
        true: ''
        false: ''
      :minimalist:
        true: ''
        false: ''
  :database_config:
    :database_choice:
      :SQLite:
        true: ''
        false: ''
      :Postgres:
        true: "-d postgresql"
        false: ''
      :MySQL:
        true: "-d mysql"
        false: ''
  :rails_flags_config:
    :guest_favorites:
      :spring:
        true: ''
        false: "--skip-spring"
      :listen:
        true: ''
        false: "--skip-listen"
      :bootsnap:
        true: ''
        false: "--skip-bootsnap"
    :starters:
      :gemfile:
        true: ''
        false: "--skip-gemfile"
      :gitignore:
        true: ''
        false: "--skip-git"
      :keep:
        true: ''
        false: "--skip-keeps"
      :bundle:
        true: ''
        false: "--skip-bundle"
      :puma:
        true: ''
        false: "--skip-puma"
    :mains:
      :actionText:
        true: ''
        false: "--skip-action-text"
      :activeRecord:
        true: ''
        false: "--skip-active-record"
      :activeStorage:
        true: ''
        false: "--skip-active-storage"
      :actionCable:
        true: ''
        false: "--skip-action-cable"
    :email:
      :actionMailer:
        true: ''
        false: "--skip-action-mailer"
      :actionMailbox:
        true: ''
        false: "--skip-action-mailbox"
    :frontend:
      :sprockets:
        true: ''
        false: "--skip-sprockets"
      :javascript:
        true: ''
        false: "--skip-javascript"
      :turbolinks:
        true: ''
        false: "--skip-turbolinks"
      :webpacker:
        true: ''
        false: "--skip-webpack-install"
      :yarn:
        true: ''
        false: "--skip-yarn"
    :testing:
      :minitest:
        true: ''
        false: "--skip-test"
      :system:
        true: ''
        false: "--skip-system-test"
:classics_tab:
  :rails_bytes_config:
    :testing:
      :Minitest:
        true: ''
        false: ''
      :RSpec:
        true: "https://www.railsbytes.com/script/VD7sra"
        false: ''
    :css_framework:
      :none:
        true: ''
        false: ''
      :TailwindCSS:
        true: "https://www.railsbytes.com/script/X8BsGy"
        false: ''
      :Bootstrap:
        true: "https://www.railsbytes.com/script/VMys5p"
        false: ''
    :frontend:
      :none:
        true: ''
        false: ''
      :Stimulus:
        true: "https://www.railsbytes.com/script/V33s33"
        false: ''
      :"Stimulus Reflex":
        true: "https://www.railsbytes.com/script/zr4s0Y"
        false: ''
        