name: Run tests + lint

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SELENIUM_URL: http://0.0.0.0:4444/wd/hub # GitLab: http://selenium__standalone-chrome:4444/wd/hub # BitBucket: http://0.0.0.0:4444/wd/hub      
    services:
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "password"
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - "5432:5432"    
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444    

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.70.0
        with:
          bundler: "Gemfile.lock"          
          bundler-cache: true

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '14'
                    
      - name: Install Yarn
        run: yarn install
        
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-        
        
      - name: Install Depencencies
        run: gem install bundler
                
      - name: Run Tests
        env:
          RAILS_ENV: test
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "password"
          POSTGRES_PORT: "5432"
        run: bundle exec rails db:create db:schema:load test:all

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: ruby/setup-ruby@v1.70.0
      with:
        bundler: "Gemfile.lock"          
        bundler-cache: true

    - name: Lint Ruby code with standardrb
      run: bundle exec standardrb
